/*
 * Particle.cpp
 *
 *  Created on: 23.02.2010
 *      Author: eckhardw
 */

#include "Particle.h"

#include "debug/debug_print.h"
#include "spdlog/spdlog.h"
#include "utils/ArrayUtils.h"
#include "utils/SpdWrapper.h"

Particle::Particle(int type_arg) {
  type = type_arg;
  // DEBUG_PRINT("Particle generated!");
  f = {0., 0., 0.};
  old_f = {0., 0., 0.};
}

Particle::Particle(const Particle &other) {
  x = other.x;
  v = other.v;
  f = other.f;
  old_f = other.old_f;
  m = other.m;
  type = other.type;
  epsilon = other.epsilon;
  sigma = other.sigma;
  // DEBUG_PRINT("Particle generated by copy!");
}

Particle::Particle(const std::array<double, 3> &x_arg,
                   const std::array<double, 3> &v_arg, const double m_arg,
                   const double _epsilon, const double _sigma, int _type) {
  x = x_arg;
  v = v_arg;
  m = m_arg;
  type = _type;
  f = {0., 0., 0.};
  old_f = {0., 0., 0.};
  sigma = _sigma;
  epsilon = _epsilon;
  // DEBUG_PRINT("Particle generated!");
}

Particle::~Particle() { /*DEBUG_PRINT("Particle destructed!");*/ }

const std::array<double, 3> &Particle::getX() const { return x; }

const std::array<double, 3> &Particle::getV() const { return v; }

const std::array<double, 3> &Particle::getF() const { return f; }

const std::array<double, 3> &Particle::getOldF() const { return old_f; }

double Particle::getM() const { return m; }

int Particle::getType() const { return type; }

double Particle::getEpsilon() const { return epsilon; }

double Particle::getSigma() const { return sigma; }

void Particle::setF(const std::array<double, 3> &F) { f = F; }

void Particle::setV(const std::array<double, 3> &V) { v = V; }

void Particle::setX(const std::array<double, 3> &X) { x = X; }

void Particle::setOldF(const dvec3 &oF) { old_f = oF; }

void Particle::setEpsilon(const double &Epsilon) { epsilon = Epsilon; }

void Particle::setSigma(const double &Sigma) { sigma = Sigma; }

void Particle::updateForceInTime() {
  old_f = f;
  f = {0., 0., 0.};
}

std::string Particle::toString() const {
  std::stringstream stream;
  stream << "Particle: X:" << x << " v: " << v << " f: " << f
         << " old_f: " << old_f << " type: " << type;
  return stream.str();
}

bool Particle::operator==(const Particle &other) const {
  return (x == other.x) and (v == other.v) and (f == other.f) and
         (type == other.type) and (m == other.m) and (old_f == other.old_f);
}

std::ostream &operator<<(std::ostream &stream, const Particle &p) {
  stream << p.toString();
  return stream;
}
